#!/bin/bash

ifconfig en0 | grep broadcast | rev | cut -d" " -f-2 | rev
# en0 car ici on est connecté via ethernet

arp -a | cut -d" " -f-2
# voir tous les appareils de notre réseau, donc ici sous-réseau
