#!/bin/bash

MIN=`grep ^UID_MIN /etc/login.defs | cut -d'	' -f4 |  cut -d' ' -f2`
MAX=`grep ^UID_MAX /etc/login.defs | cut -d'	' -f4 |  cut -d' ' -f2`
eval getent passwd {$MIN..$MAX} | cut -d':' -f1

# Numéros des UID des utilisateurs réels sont fixés par le fichier /etc/login.defs, donc -> getent passwd {1000..60000} + cut name

# while ((MIN <= $MAX))
# do
# 	getent passwd $i
# 	((MIN += 1))
# done
#
#
